import React, { useState, useEffect, useRef } from 'react';
import { User, DMThread, DirectMessage } from '../types';
import { Send, X, Search, Circle } from 'lucide-react';

interface DirectMessagingProps {
  currentUser: User;
  users: User[];
  threads: DMThread[];
  onClose: () => void;
  onSendMessage: (threadId: string, content: string) => void;
  onCreateThread: (targetUserId: string) => void;
}

export const DirectMessaging: React.FC<DirectMessagingProps> = ({ 
  currentUser, 
  users, 
  threads, 
  onClose, 
  onSendMessage,
  onCreateThread 
}) => {
  const [activeThreadId, setActiveThreadId] = useState<string | null>(null);
  const [input, setInput] = useState('');
  const [searchTerm, setSearchTerm] = useState('');
  const scrollRef = useRef<HTMLDivElement>(null);

  const activeThread = threads.find(t => t.id === activeThreadId);
  
  // Identify the "other" user in the active thread
  const activeOtherUserId = activeThread 
    ? activeThread.participantIds.find(id => id !== currentUser.id) 
    : null;
  const activeOtherUser = users.find(u => u.id === activeOtherUserId);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [activeThread?.messages]);

  const handleSend = () => {
    if (!input.trim() || !activeThreadId) return;
    onSendMessage(activeThreadId, input);
    setInput('');
  };

  const handleUserSelect = (targetId: string) => {
    // Check if thread exists
    const existing = threads.find(t => t.participantIds.includes(targetId) && t.participantIds.includes(currentUser.id));
    if (existing) {
      setActiveThreadId(existing.id);
    } else {
      onCreateThread(targetId);
      // We assume the parent updates the threads list, but for now we wait for update or predict ID
      // For simplicity in this mock, we predict the ID usually generated by parent
      // But ideally we wait. We'll set it in effect or parent callback.
    }
  };

  const filteredUsers = users.filter(u => 
    u.id !== currentUser.id && 
    u.name.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
      <div className="bg-fantasy-900 w-full max-w-4xl h-[600px] rounded-xl border border-fantasy-700 shadow-2xl flex overflow-hidden">
        
        {/* Sidebar: User List */}
        <div className="w-1/3 bg-fantasy-800 border-r border-fantasy-700 flex flex-col">
          <div className="p-4 border-b border-fantasy-700 flex justify-between items-center">
            <h2 className="text-white font-serif font-bold">Messages</h2>
            <div className="relative">
              <Search size={14} className="absolute left-2 top-2 text-fantasy-muted" />
              <input 
                className="w-full bg-fantasy-900 border border-fantasy-700 rounded-full py-1 pl-7 pr-2 text-xs text-white focus:border-fantasy-accent outline-none"
                placeholder="Find user..."
                value={searchTerm}
                onChange={e => setSearchTerm(e.target.value)}
              />
            </div>
          </div>
          
          <div className="flex-1 overflow-y-auto">
            {filteredUsers.map(user => {
              // Find thread summary
              const thread = threads.find(t => t.participantIds.includes(user.id));
              const lastMsg = thread?.messages[thread.messages.length - 1];

              return (
                <div 
                  key={user.id}
                  onClick={() => handleUserSelect(user.id)}
                  className={`p-3 flex items-center gap-3 cursor-pointer hover:bg-fantasy-700 transition-colors ${activeOtherUserId === user.id ? 'bg-fantasy-700' : ''}`}
                >
                  <div className="relative">
                    <img src={user.avatarUrl} alt={user.name} className="w-10 h-10 rounded-full object-cover border border-fantasy-600" />
                    <div className={`absolute bottom-0 right-0 w-3 h-3 rounded-full border-2 border-fantasy-800 ${user.status === 'online' ? 'bg-green-500' : user.status === 'in-game' ? 'bg-purple-500' : 'bg-gray-500'}`} />
                  </div>
                  <div className="flex-1 overflow-hidden">
                    <div className="flex justify-between items-center mb-0.5">
                      <span className="font-bold text-white text-sm truncate">{user.name}</span>
                      {thread && thread.lastUpdated > 0 && (
                        <span className="text-[10px] text-fantasy-muted">{new Date(thread.lastUpdated).toLocaleDateString()}</span>
                      )}
                    </div>
                    <p className={`text-xs truncate ${thread?.unreadCount ? 'text-fantasy-accent font-bold' : 'text-fantasy-muted'}`}>
                      {lastMsg ? lastMsg.content : "Start a conversation"}
                    </p>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Main: Chat Area */}
        <div className="flex-1 flex flex-col bg-fantasy-900 relative">
          {/* Header */}
          <div className="p-4 border-b border-fantasy-700 flex justify-between items-center bg-fantasy-800/50">
            {activeOtherUser ? (
              <div className="flex items-center gap-3">
                 <img src={activeOtherUser.avatarUrl} className="w-8 h-8 rounded-full" />
                 <div>
                   <h3 className="text-white font-bold">{activeOtherUser.name}</h3>
                   <span className="text-xs text-fantasy-muted capitalize flex items-center gap-1">
                     <Circle size={8} fill="currentColor" className={activeOtherUser.status === 'online' ? 'text-green-500' : activeOtherUser.status === 'in-game' ? 'text-purple-500' : 'text-gray-500'} />
                     {activeOtherUser.status}
                   </span>
                 </div>
              </div>
            ) : (
              <div className="text-fantasy-muted text-sm">Select a user to message</div>
            )}
            <button onClick={onClose} className="text-fantasy-muted hover:text-white p-2">
              <X size={20} />
            </button>
          </div>

          {/* Messages */}
          <div className="flex-1 overflow-y-auto p-4 space-y-4" ref={scrollRef}>
            {activeThread ? (
              activeThread.messages.map(msg => {
                const isMe = msg.senderId === currentUser.id;
                return (
                  <div key={msg.id} className={`flex ${isMe ? 'justify-end' : 'justify-start'}`}>
                    <div className={`max-w-[70%] px-4 py-2 rounded-2xl text-sm ${isMe ? 'bg-fantasy-accent text-fantasy-900 rounded-tr-none' : 'bg-fantasy-800 border border-fantasy-700 text-fantasy-text rounded-tl-none'}`}>
                      {msg.content}
                    </div>
                  </div>
                );
              })
            ) : (
               <div className="flex flex-col items-center justify-center h-full text-fantasy-muted opacity-50">
                 <Search size={48} className="mb-2" />
                 <p>Select a contact to start chatting</p>
               </div>
            )}
          </div>

          {/* Input */}
          <div className="p-4 border-t border-fantasy-700 bg-fantasy-800">
            <div className="flex gap-2">
              <input 
                className="flex-1 bg-fantasy-900 border border-fantasy-700 rounded-lg px-4 py-2 text-white outline-none focus:border-fantasy-accent"
                placeholder="Type a message..."
                value={input}
                onChange={e => setInput(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && handleSend()}
                disabled={!activeThreadId}
              />
              <button 
                onClick={handleSend} 
                disabled={!input.trim() || !activeThreadId}
                className="p-2 bg-fantasy-accent text-fantasy-900 rounded-lg hover:bg-opacity-90 disabled:opacity-50"
              >
                <Send size={18} />
              </button>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
};